[theme]

# Primary accent for interactive elements
primaryColor = '#4A65D1'

# Background color for the main content area
backgroundColor = '#272E4A'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1B2034'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"